In [352]:
import numpy as np
x=np.array([[1,2,3], [4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [353]:
import numpy as np
x=np.zeros((10))
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [354]:
import numpy as np
x=10 + np.arange(40)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [51]:
import numpy as np
x=10 + np.arange(40)
print(x.shape)

(40,)


In [52]:
import numpy as np
x=10+ np.arange(40)
type(x)

numpy.ndarray

In [23]:
import numpy as np
print(np._version_)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/zeesh/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/zeesh/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/zeesh/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

In [31]:
import numpy as np
x=np.zeros((10))
x.ndim

1

In [38]:
import numpy as np
x=np.array([[1,2,3], [4,5,6],[7,8,9]])
bool_array=(x>0)
print(bool_array)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [41]:
# Two Dimentional Array
import numpy as np
x=np.array([[1,2,3], [4,5,6]])
print(x)
print(x.shape)
print(x.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int32


In [42]:
#Three Dimentional Array
import numpy as np
x=np.array([[1,2,3], [4,5,6],[7,8,9]])
print(x)
print(x.shape)
print(x.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
int32


In [46]:
#Reverse a vector (first element becomes last)
import numpy as np
x=np.arange(1,10)
print("Original Array")
print(x)
print("Reverse Array")
x=x[::-1]
print(x)


Original Array
[1 2 3 4 5 6 7 8 9]
Reverse Array
[9 8 7 6 5 4 3 2 1]


In [60]:
#Create a null vector of size 10 but the fifth value which is 1
import numpy as np
x=np.arange(10)
print("Without Modification")
print(x)
print("Print 1 at 5th index")
x[5]=1
print(x)


Without Modification
[0 1 2 3 4 5 6 7 8 9]
Print 1 at 5th index
[0 1 2 3 4 1 6 7 8 9]


In [61]:
#Create a 3x3 identity matrix
import numpy as np
x=np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [66]:
#Convert the data type of the given array from int to float
import numpy as np
arr=np.array([1,2,3,4,5])
print("Integer Type Array")
print(arr)
print("Float Type Array")
x=dtype=np.float64(arr)
print(x)

Integer Type Array
[1 2 3 4 5]
Float Type Array
[1. 2. 3. 4. 5.]


In [76]:
#Multiply arr1 with arr2
import numpy as np
arr1=np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
arr2=np.array([[0.0,4.0,1.0],[7.0,2.0,12.0]])
print("1st way of Multiplication")
print(arr1*arr2)
print("2nd way of Multiplication")
arr= np.multiply(arr1,arr2)
print(arr)

1st way of Multiplication
[[ 0.  8.  3.]
 [28. 10. 72.]]
2nd way of Multiplication
[[ 0.  8.  3.]
 [28. 10. 72.]]


In [90]:
#Make an array by comparing both the arrays provided above
import numpy as np
arr1=np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
arr2=np.array([[0.0,4.0,1.0],[7.0,2.0,12.0]])
print("arr1 > arr2")
print(np.greater(arr1, arr2))
print("arr1 >= arr2")
print(np.greater_equal(arr1, arr2))
print("arr1 < arr2")
print(np.less(arr1, arr2))
print("arr1 <= arr2")
print(np.less_equal(arr1, arr2))


arr1 > arr2
[[ True False  True]
 [False  True False]]
arr1 >= arr2
[[ True False  True]
 [False  True False]]
arr1 < arr2
[[False  True False]
 [ True False  True]]
arr1 <= arr2
[[False  True False]
 [ True False  True]]


In [129]:
#Extract all odd numbers from arr with values(0-9)
import numpy as np 
 
data=np.arange(1,10,dtype=int) 
for i in range(len(data)): 
    if(i%2==1): 
        data[i]=i
print(data) 

[1 1 3 3 5 5 7 7 9]


In [127]:
#Replace all odd numbers to -1 from previous array
import numpy as np 
 
data=np.arange(1,10,dtype=int) 
for i in range(len(data)): 
    if(i%2==0): 
        data[i]=-1
print(data) 

[-1  2 -1  4 -1  6 -1  8 -1]


In [135]:
#Replace the values of indexes 5,6,7 and 8 to 12
import numpy as np
arr = np.arange(10)
arr[5]=12
arr[6]=12
arr[7]=12
arr[8]=12
print(arr)

[ 0  1  2  3  4 12 12 12 12  9]


In [139]:
#Create a 2d array with 1 on the border and 0 inside
import numpy as np
x = np.ones((5,5))
print("Original")
print(x)
print("1 on Border and 0 Inside the array")
x[1:-1,1:-1] = 0
print(x)

Original
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on Border and 0 Inside the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [143]:
#Replace the value 5 to 12
import numpy as np
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)
arr2d[1,1]=12
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


In [147]:
#Convert all the values of 1st array to 64
import numpy as np
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("Original Array")
print(arr3d)
print("After Correction")
arr3d[0,0]=[64]
print(arr3d)

Original Array
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
After Correction
[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [151]:
# Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it
import numpy as np
arr2d = np.array([[11, 22, 33],
                [44, 55, 66],
                [77, 88, 99]])

a, b = data[:, :-1], data[:, -1]
print("2D Array")
print(a)
print("1D Array")
print(b)


2D Array
[[11 22]
 [44 55]
 [77 88]]
1D Array
[33 66 99]


In [157]:
#Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it
import numpy as np
arr2d = np.array([[11, 22, 33],
                [44, 55, 66],
                [77, 88, 99]])

a = data[:1:],
print("1D Array")
print(a)

1D Array
(array([[11, 22, 33]]),)


In [209]:
#Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it
import numpy as np
arr2d= np.array([[1,2,3], [4,5,6],[7,8,9]])
print(arr2d)
print("After Slicing")
a=arr2d[1,1]
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
After Slicing
5


In [234]:
#Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows
import numpy as np
arr2d= np.array([[1,2,3], [4,5,6],[7,8,9]])
print(arr2d)
c=arr2d[:2,:-1]
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]


In [240]:
#Create a 10x10 array with random values and find the minimum and maximum values
import numpy as np
arr10d=np.random.random((10,10))
print(arr10d)

[[0.06819189 0.45980522 0.50991351 0.43574775 0.11889514 0.72118088
  0.98540359 0.80397642 0.23224685 0.01815713]
 [0.62853662 0.01482259 0.10111638 0.87411826 0.20172808 0.5853469
  0.75831817 0.55133295 0.90218953 0.26381665]
 [0.80934585 0.03316998 0.35775844 0.39211074 0.55799798 0.81538983
  0.78929348 0.52011194 0.70158491 0.60977601]
 [0.23191681 0.89933632 0.70578586 0.52510534 0.59465588 0.53353497
  0.64943515 0.26938308 0.45114626 0.75943311]
 [0.69545561 0.5453858  0.08827589 0.160162   0.67565117 0.51502732
  0.74394111 0.77376936 0.51095471 0.31288724]
 [0.27365073 0.58243553 0.93772444 0.69057884 0.33149603 0.97433538
  0.97626752 0.20153488 0.41604934 0.78505583]
 [0.46192554 0.25296073 0.65279407 0.9682709  0.1057182  0.15477567
  0.01357501 0.82064575 0.33492676 0.97775404]
 [0.45397476 0.29995433 0.44856302 0.77839759 0.67469126 0.84192893
  0.98177716 0.43196317 0.54310154 0.52437659]
 [0.46867202 0.81085723 0.7113812  0.24340465 0.60120406 0.7225453
  0.69456659 0

In [248]:
#Find the common items between a and b
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


In [252]:
#Find the positions where elements of a and b match
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where((np.in1d(a,b))))

(array([1, 3, 5, 7], dtype=int64),)


In [256]:
#Find all the values from array data where the values from array names are not equal to Will
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
x=np.where(names!='Will')
print(x)

(array([0, 1, 3, 5, 6], dtype=int64),)


In [272]:
#Find all the values from array data where the values from array names are not equal to Will and Joe

import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
x=np.where(names!='Will')
y=np.where(names!='Joe')
print(x,y)

(array([0, 1, 3, 5, 6], dtype=int64),) (array([0, 2, 3, 4], dtype=int64),)


In [279]:
#Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.
import numpy as np
x=np.random.rand(5, 3) * 5 + 10
print(x)

[[10.76451132 10.32638773 13.21952479]
 [13.41888659 11.70929644 12.24191626]
 [10.84661651 12.06055156 10.69730883]
 [12.67617489 13.78982364 14.70633519]
 [13.87953706 11.35268244 10.28007509]]


In [276]:
#Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.
import numpy as np
x=np.random.rand(2,2,4) * 5 + 11
print(x)

[[[14.62909171 14.59034474 12.33058479 14.09858614]
  [11.03368957 11.94120756 15.85804425 12.97585386]]

 [[11.39797076 15.92870304 12.16852084 11.17006843]
  [12.2068027  11.07268573 15.32880846 11.22922535]]]


In [282]:
#Swap axes of the array you created in Question 32
import numpy as np
x=np.random.rand(2,2,4) * 5 + 11
y=np.swapaxes(x,0,2)
print(x)
print("After Swaping Axes")
print(y)

[[[12.91689216 14.47082654 13.27565248 15.11855754]
  [12.16255446 12.94044336 13.73923622 11.11064539]]

 [[13.09787191 13.99985006 13.97813282 11.37991264]
  [11.39593572 12.5964635  12.29539837 12.5875311 ]]]
After Swaping Axes
[[[12.91689216 13.09787191]
  [12.16255446 11.39593572]]

 [[14.47082654 13.99985006]
  [12.94044336 12.5964635 ]]

 [[13.27565248 13.97813282]
  [13.73923622 12.29539837]]

 [[15.11855754 11.37991264]
  [11.11064539 12.5875311 ]]]


In [293]:
#Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0
import numpy as np
x=np.arange(10)
print("Original Array")
print(x)
y=np.sqrt(x)
print("After Square Root")
print(y)
print("After Applying Condition")
for i in range(len(data)): 
    if(i<0.5): 
        data[i]=0
print(data)


Original Array
[0 1 2 3 4 5 6 7 8 9]
After Square Root
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
After Applying Condition
[[ 0.          0.          0.          0.        ]
 [-0.64604532 -0.76443796  2.20187849 -2.10172007]
 [-1.         -1.         -1.         -1.        ]
 [-1.08410373 -0.93007367  0.50688656  1.28851229]
 [-1.         -1.         -1.         -1.        ]
 [-0.59500481  1.7015241   0.18304927  0.74216237]
 [-1.         -1.         -1.         -1.        ]]


In [303]:
#Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays
import numpy as np
arr1=np.random.random(12)
arr2=np.random.random(12)
print(arr1)
print(arr2)

z=np.maximum(arr1,arr2)
print("Maximum Array Will be")
print(z)

[0.6601434  0.25674036 0.22356101 0.44833275 0.06917635 0.37360457
 0.10650809 0.24798845 0.53268024 0.12952519 0.44110533 0.54795965]
[0.83601116 0.36252003 0.73364968 0.20324979 0.33856594 0.80360597
 0.78552783 0.21141557 0.3731133  0.10522006 0.02129036 0.95495652]
Maximum Array Will be
[0.83601116 0.36252003 0.73364968 0.44833275 0.33856594 0.80360597
 0.78552783 0.24798845 0.53268024 0.12952519 0.44110533 0.95495652]


In [310]:
#Find the unique names and sort them out
import numpy as np
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print("Before Unique & Sort")
print(names)
y=np.unique(names)
z=np.sort(y)
print("After Unique Command")
print(y)
print("After Sort Command")
print(z)

Before Unique & Sort
['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
After Unique Command
['Bob' 'Joe' 'Will']
After Sort Command
['Bob' 'Joe' 'Will']


In [313]:
#From array a remove all items present in array b
import numpy as np
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
c=np.setdiff1d(a,b)
print(c)


[1 2 3 4]


In [338]:
#Following is the input NumPy array delete column two and insert following new column in its place.
import numpy as np
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
print("Original Array")
print(sampleArray)
print("After Removing Column 2")
a_del = np.delete(sampleArray, 1, 1)
print(a_del)
print("After Adding Column 2")
a_add = np.insert(sampleArray,1,1)
print(a_add)
newArray = np.append(sampleArray, [[50, 60, 70]], axis = 0)
print(newArray)

Original Array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
After Removing Column 2
[[34 73]
 [82 12]
 [53 66]]
After Adding Column 2
[34  1 43 73 82 22 12 53 94 66]
[[34 43 73]
 [82 22 12]
 [53 94 66]
 [50 60 70]]


In [344]:
import numpy as np
a = np.array([[34,43,73],[82,22,12],[53,94,66]])
b = np.array([[10,10,10]])
print(np.append(a, b, axis=0))

[[34 43 73]
 [82 22 12]
 [53 94 66]
 [10 10 10]]


In [347]:
#Find the dot product of the above two matrix
import numpy as np
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z=np.dot(x,y)
print(z)

[[ 28.  64.]
 [ 67. 181.]]


In [350]:
#Generate a matrix of 20 random values and find its cumulative sum
import numpy as np
arr=np.random.random(20)
print(arr)
print("After Sum")
arrresult=np.cumsum(arr)
print(arrresult)


[0.70761282 0.48063259 0.58757586 0.34713172 0.30283028 0.13377783
 0.50631598 0.60380354 0.58123122 0.99673746 0.33624821 0.5357268
 0.6384262  0.52763999 0.36144787 0.83922413 0.86905473 0.06368394
 0.08778199 0.08547185]
After Sum
[0.70761282 1.18824541 1.77582127 2.122953   2.42578328 2.55956111
 3.0658771  3.66968064 4.25091186 5.24764933 5.58389754 6.11962434
 6.75805054 7.28569052 7.64713839 8.48636252 9.35541725 9.41910119
 9.50688318 9.59235503]
